FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY backend ./backend

EXPOSE 8501

CMD ["streamlit", "run", "backend/dashboard/dashboard.py", "--server.address=0.0.0.0", "--server.port=8501", "--server.headless=true"]
